import { MigrationInterface, QueryRunner } from "typeorm";

export class default1678799810646 implements MigrationInterface {
    name = 'default1678799810646'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "vane_companhiaAerea" ("codigoCompanhia" number GENERATED BY DEFAULT AS IDENTITY, "nomeCompanhia" varchar2(255) NOT NULL, "nomeAeroporto" varchar2(255) NOT NULL, CONSTRAINT "PK_e358552939d518631f0a7da63e9" PRIMARY KEY ("codigoCompanhia"))`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" MODIFY "codigoVoo" number  `);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" ADD CONSTRAINT "PK_01f2497e7e56bb372f58a651f19" PRIMARY KEY ("codigoVoo")`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" ADD "nome" varchar2(255) NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vane_passageiros" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" ADD "nome" nvarchar2(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" DROP CONSTRAINT "PK_01f2497e7e56bb372f58a651f19"`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" MODIFY "codigoVoo" number  `);
        await queryRunner.query(`DROP TABLE "vane_companhiaAerea"`);
    }

}
