import { MigrationInterface, QueryRunner } from "typeorm";

export class default1678795495883 implements MigrationInterface {
    name = 'default1678795495883'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "vane_cargos" ("codigo" number GENERATED BY DEFAULT AS IDENTITY, "nome" varchar2(255) NOT NULL, "descricao" varchar2(255), CONSTRAINT "PK_8e7a083c24af8d7c67b56231e55" PRIMARY KEY ("codigo"))`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" MODIFY "codigoVoo" number  `);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" ADD CONSTRAINT "PK_01f2497e7e56bb372f58a651f19" PRIMARY KEY ("codigoVoo")`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" ADD "nome" varchar2(255) NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vane_passageiros" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" ADD "nome" nvarchar2(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" DROP CONSTRAINT "PK_01f2497e7e56bb372f58a651f19"`);
        await queryRunner.query(`ALTER TABLE "vane_passageiros" MODIFY "codigoVoo" number  `);
        await queryRunner.query(`DROP TABLE "vane_cargos"`);
    }

}
